### ISSUE TITLE
ERROR Error watching file for changes: EMFILE

### ISSUE THREAD

**Issue by shihasck** [thanhtungdp/react-native-login-animated#6]
>  ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1018:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1420:11)  

I'm getting this error on running IOS simulator.
`react-native run-ios`

**Comment by matr1xp** [comment]
This error has something to do with watchman. Try reinstalling it or follow instructions here:
https://github.com/facebook/react-native/issues/910

**Comment by shihasck** [comment]
It fixed that issue.
